<!DOCTYPE html>
<html lang="pt-pt">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Lista de tarefas com MVC</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
    <script
      src="https://kit.fontawesome.com/6e8691900f.js"
      crossorigin="anonymous"
    ></script>

    <script>
      function marcarRealizada(id) {
        window.location = "/marcar_tarefa?id=" + id;
      }

      function renomear(id, conteudoTarefa) {
        let tarefa = document.getElementById("tarefa_" + id);

        let form = document.createElement("form");
        form.action = "/renomear_tarefa?id=" + id;
        form.method = "post";
        form.className = "input-group";

        let input = document.createElement("input");
        input.type = "text";
        input.name = "tarefa";
        input.className = "form-control";
        input.value = tarefa.innerText;

        let inputHidden = document.createElement("input");
        inputHidden.type = "hidden";
        inputHidden.name = "id_tarefa";
        inputHidden.value = id;

        let btn = document.createElement("button");
        btn.type = "submit";
        btn.className = "btn btn-dark text-white";
        btn.innerText = "Atualizar";

        form.appendChild(input);
        form.appendChild(inputHidden);
        form.appendChild(btn);

        tarefa.innerHTML = "";
        tarefa.append(form);
      }

      function apagar(id) {
        window.location = "/eliminar_tarefa?id=" + id;
      }
    </script>
  </head>
  <body>
    <div class="container mt-5">
      <div class="row">
        <div class="col-md-4">
          <div class="card bg-primary text-white">
            <div class="card-header">Tarefas pendentes</div>
            <div class="card-body row">
              <?php foreach($this->view->tarefa as $tarefa) { ?>

              <?php if($tarefa['id_status'] == 1) { ?>

              <?php if($tarefa['origem'] == $_SESSION['id']) { ?>

              <div class="col-md-8" id="tarefa_<?=$tarefa['id']?>">
                <?= $tarefa['nome'] ?>
              </div>
              <div class="col-md-4">
                <i
                  onclick="marcarRealizada(<?= $tarefa['id'] ?>)"
                  class="fa-solid fa-lg ms-2 fa-check"
                ></i>
                <i
                  onclick="renomear(<?= $tarefa['id'] ?>)"
                  class="fa-solid fa-lg ms-2 fa-delete-left"
                ></i>
                <i
                  onclick="apagar(<?= $tarefa['id']?>)"
                  class="fa-sharp fa-lg ms-2 fa-solid fa-trash"
                ></i>
              </div>

              <?php } ?>

              <?php } ?>

              <?php } ?>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card">
            <div class="card-header">Adicionar tarefas</div>
            <div class="card-body">
              <form action="/inserir_tarefa" method="post" class="form-group">
                <div class="row">
                  <div class="col-md-8 pe-0">
                    <input
                      class="form-control"
                      type="text"
                      name="tarefa"
                      placeholder="Tarefa..."
                      required
                    />
                  </div>
                  <div class="col-md-4">
                    <button type="submit" class="btn btn-secondary m-0">
                      Submeter
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card bg-dark text-white">
            <div class="card-header">Tarefas realizadas</div>
            <div class="card-body row">
              <?php foreach($this->view->tarefa as $tarefa) { ?>

              <?php if($tarefa['id_status'] == 0) { ?>

              <?php if($tarefa['origem'] == $_SESSION['id']) { ?>

              <div
                class="col-md-8"
                id="tarefa_<?=$tarefa['id']?>"
                style="text-decoration: line-through"
              >
                <?= $tarefa['nome'] ?>
              </div>
              <div class="col-md-4">
                <i
                  onclick="apagar(<?= $tarefa['id'] ?> )"
                  class="fa-sharp fa-lg ms-2 fa-solid fa-trash"
                ></i>
              </div>

              <?php } ?>

              <?php } ?>

              <?php } ?>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
