<!DOCTYPE html>
<html lang="pt-pt">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Criar Conta</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container mt-5">
      <div class="row">
        <div class="card mx-auto" style="width: 800px">
          <div class="card-body">
            <h2 class="display-4 text-center mt-4">Fazer login</h2>
            <form action="/autenticar" method="post" class="mt-5 form-group">
              <input
                type="email"
                class="form-control mt-4"
                placeholder="Email"
                name="email"
                required
              />
              <input
                type="password"
                class="form-control mt-4"
                placeholder="Senha"
                name="senha"
                required
              />
              <button
                type="submit"
                class="d-block mx-auto btn btn-lg btn-primary mt-4"
              >
                Logar
              </button>
              <small class="mt-2">
                Não tens conta? clica <a href="/login">aqui</a> para criares!
              </small>
            </form>
          </div>
        </div>
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>
