<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Gestor de tarefas com o MVC</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container">
        <a class="navbar-brand fs-2" href="/">Gestor de tarefas</a>
        <div class="ms-auto me-2">
          <a href="/criar_conta" class="btn btn-outline-dark"> Criar conta </a>
          <a href="/" class="btn btn-outline-dark ms-3"> Fazer login </a>
        </div>
      </div>
    </nav>

    <?php $this->content() ?>

    <footer class="bg-dark text-white p-4 fixed-bottom">
      <div class="container">
        <div class="row">
          <h4 class="text-center">&copy; Pedro Matos 2023</h4>
        </div>
      </div>
    </footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>
